// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBap6gQvT5GfbOT0fch1_fVVj6Zsnqdp18',
    appId: '1:559499110439:web:b28267e72597f915bb4602',
    messagingSenderId: '559499110439',
    projectId: 'atw-task-12-12',
    authDomain: 'atw-task-12-12.firebaseapp.com',
    storageBucket: 'atw-task-12-12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjEchZMPTvFsCY2KQqFuUYZA6UIDAjGQY',
    appId: '1:559499110439:android:65cf274a213fcfbdbb4602',
    messagingSenderId: '559499110439',
    projectId: 'atw-task-12-12',
    storageBucket: 'atw-task-12-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKufDTePOmaRSqNw4ME3N8hI7B1Ivxrc',
    appId: '1:559499110439:ios:ee2ec757e2b9ca0bbb4602',
    messagingSenderId: '559499110439',
    projectId: 'atw-task-12-12',
    storageBucket: 'atw-task-12-12.firebasestorage.app',
    iosBundleId: 'com.example.atwTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNKufDTePOmaRSqNw4ME3N8hI7B1Ivxrc',
    appId: '1:559499110439:ios:ee2ec757e2b9ca0bbb4602',
    messagingSenderId: '559499110439',
    projectId: 'atw-task-12-12',
    storageBucket: 'atw-task-12-12.firebasestorage.app',
    iosBundleId: 'com.example.atwTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBap6gQvT5GfbOT0fch1_fVVj6Zsnqdp18',
    appId: '1:559499110439:web:658c059057774fb9bb4602',
    messagingSenderId: '559499110439',
    projectId: 'atw-task-12-12',
    authDomain: 'atw-task-12-12.firebaseapp.com',
    storageBucket: 'atw-task-12-12.firebasestorage.app',
  );
}
